name: Lint and Test

on:
  push:
    branches-ignore:
      - "master"
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"

      - name: Dependencies
        run: npm ci

      - name: Tests
        run: npm run test

      - name: Publish
        run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
