name: Lint and Test

on:
  push:
    branches-ignore:
      - "master"
      - "main"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"

      - name: Dependencies
        run: npm ci

      - name: Tests
        run: npm run test

      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: "Automated Version Bump"
        run: npx auto-version --patch

      - name: "Commit Version Bump"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          git add package.json
          git commit -m "Version Bump"
          git push origin dev

      - name: Publish
        run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
