name: Lint, Test, and Publish

on:
  push:
    branches:
      - "dev"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          scope: "@ochom"

      - name: Dependencies
        run: npm ci

      - name: Tests
        run: npm run test
